site_name: MkDocs Tutorial

nav:
  - Home: 'index.md'
  - 'User Guide':
    - 'Getting Started': getting-started.md
    - Options: configuration-options.md
  - About: 'about.md'
  - License: 'license.md'
